name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5

      - run: npm i -g pnpm@8

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: install
        run: pnpm i

      - name: build
        run: |
          pnpm build

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: harbor.ncuos.com/incu-be/incu-fe

      - name: Build Docker Image and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Deployment
        uses: MultiMx/K8sSetImageAction@v0.5
        with:
          backend: "https://rancher.ncuos.com"
          token: ${{ secrets.RANCHER_TOKEN }}
          namespace: incu-be
          workload: incu-fe
          image: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
